// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskEvidence.Data;

#nullable disable

namespace TaskEvidence.Server.Migrations
{
    [DbContext(typeof(EvidenceDbContext))]
    partial class EvidenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskEvidence.Models.ChecklistModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Deadline")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskChecklist", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deadline = new DateTime(2024, 2, 26, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Workflow: Code-First\nTyp databáze: Microsoft SQL Server (SSMS 2018)",
                            DoneAt = new DateTime(2024, 2, 23, 20, 12, 40, 418, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Vytvoření databáze",
                            TaskId = 1
                        },
                        new
                        {
                            Id = 2,
                            Deadline = new DateTime(2024, 2, 27, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Technologie: FluentAPI\nJazyk C#",
                            DoneAt = new DateTime(2024, 2, 23, 20, 12, 40, 418, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Vytvoření datového modelu",
                            TaskId = 1
                        },
                        new
                        {
                            Id = 3,
                            Deadline = new DateTime(2024, 2, 28, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Framework: Blazor",
                            DoneAt = new DateTime(2024, 2, 23, 20, 12, 40, 418, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Návrh oken",
                            TaskId = 1
                        },
                        new
                        {
                            Id = 4,
                            Deadline = new DateTime(2024, 3, 1, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            DoneAt = new DateTime(2024, 2, 23, 20, 12, 40, 418, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Odladění bugů",
                            TaskId = 1
                        },
                        new
                        {
                            Id = 5,
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Aby se v databázi ukládal i čas",
                            Priority = 2,
                            Status = 2,
                            StepName = "Upravení formátu",
                            TaskId = 4
                        },
                        new
                        {
                            Id = 6,
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Description => Name",
                            Priority = 3,
                            Status = 2,
                            StepName = "Tabulka: Tasks",
                            TaskId = 5
                        },
                        new
                        {
                            Id = 7,
                            Deadline = new DateTime(2024, 2, 26, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Tak aby mohl obsahovat null hodnoty (nullable)",
                            DoneAt = new DateTime(2024, 2, 23, 20, 8, 16, 719, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Sloupec: Description",
                            TaskId = 6
                        },
                        new
                        {
                            Id = 8,
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            DoneAt = new DateTime(2024, 2, 23, 20, 8, 33, 381, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Seznam všech úkolů",
                            TaskId = 7
                        },
                        new
                        {
                            Id = 9,
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            DoneAt = new DateTime(2024, 2, 23, 20, 8, 33, 381, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Seznam úkolů konkrétního zadavatele",
                            TaskId = 7
                        },
                        new
                        {
                            Id = 10,
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            DoneAt = new DateTime(2024, 2, 23, 20, 8, 33, 381, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Seznam úkolů konkrétního řešitele",
                            TaskId = 7
                        },
                        new
                        {
                            Id = 11,
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            DoneAt = new DateTime(2024, 2, 23, 20, 8, 33, 381, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Nevyřešené úkoly",
                            TaskId = 7
                        },
                        new
                        {
                            Id = 12,
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            DoneAt = new DateTime(2024, 2, 23, 20, 8, 33, 381, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Nevyřešené úkoly, po termínu",
                            TaskId = 7
                        },
                        new
                        {
                            Id = 13,
                            Deadline = new DateTime(2024, 2, 24, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "které obsahují nějaký bod z checklistu po termínu.",
                            Priority = 1,
                            Status = 2,
                            StepName = "Nevyřešené úkoly",
                            TaskId = 7
                        },
                        new
                        {
                            Id = 14,
                            Deadline = new DateTime(2024, 2, 27, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Vytvořit logiku pro zahození neuložených dat do Local/Session storage, tak aby se po refreshu stránky smazala",
                            Priority = 1,
                            Status = 2,
                            StepName = "Logika pro zahození dat",
                            TaskId = 8
                        },
                        new
                        {
                            Id = 15,
                            Deadline = new DateTime(2024, 2, 28, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Z disabled => readonly",
                            Priority = 3,
                            Status = 3,
                            StepName = "Změna tagů",
                            TaskId = 9
                        },
                        new
                        {
                            Id = 16,
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            DoneAt = new DateTime(2024, 2, 23, 20, 9, 0, 380, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Čtení dokumentace",
                            TaskId = 10
                        },
                        new
                        {
                            Id = 17,
                            Deadline = new DateTime(2024, 2, 27, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Změna typu na webassembly z důvodu nefunkčnosti v původním Blazor Server App.\n*Spontánní naříkání*",
                            DoneAt = new DateTime(2024, 2, 23, 20, 9, 0, 380, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Změna typu projektu",
                            TaskId = 10
                        },
                        new
                        {
                            Id = 18,
                            Deadline = new DateTime(2024, 2, 29, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            DoneAt = new DateTime(2024, 2, 23, 20, 9, 19, 487, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Controller",
                            TaskId = 11
                        },
                        new
                        {
                            Id = 19,
                            Deadline = new DateTime(2024, 2, 29, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            DoneAt = new DateTime(2024, 2, 23, 20, 9, 19, 487, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Service",
                            TaskId = 11
                        },
                        new
                        {
                            Id = 20,
                            Deadline = new DateTime(2024, 2, 29, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            DoneAt = new DateTime(2024, 2, 23, 20, 9, 19, 487, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Interface",
                            TaskId = 11
                        },
                        new
                        {
                            Id = 21,
                            Deadline = new DateTime(2024, 2, 28, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            DoneAt = new DateTime(2024, 2, 23, 20, 9, 39, 884, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Hledání příčiny",
                            TaskId = 12
                        },
                        new
                        {
                            Id = 22,
                            Deadline = new DateTime(2024, 2, 28, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Změna TaskModel task na nullable objekt",
                            DoneAt = new DateTime(2024, 2, 23, 20, 9, 39, 884, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Změna datového typu",
                            TaskId = 12
                        },
                        new
                        {
                            Id = 23,
                            Deadline = new DateTime(2024, 2, 28, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Přidání attributu JsonIgnore",
                            DoneAt = new DateTime(2024, 2, 23, 20, 9, 39, 884, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Přidání attributu",
                            TaskId = 12
                        },
                        new
                        {
                            Id = 24,
                            Deadline = new DateTime(2024, 2, 24, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            DoneAt = new DateTime(2024, 2, 23, 20, 10, 2, 584, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Stránka detail",
                            TaskId = 14
                        },
                        new
                        {
                            Id = 25,
                            Deadline = new DateTime(2024, 2, 24, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 2,
                            StepName = "WorkflowItem",
                            TaskId = 14
                        },
                        new
                        {
                            Id = 26,
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "K jednotlivým konfiguracím přidat simulovaná data.",
                            DoneAt = new DateTime(2024, 2, 23, 20, 10, 23, 605, DateTimeKind.Unspecified),
                            Priority = 3,
                            Status = 1,
                            StepName = "Postup",
                            TaskId = 15
                        },
                        new
                        {
                            Id = 27,
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Ke každému úkolu přidat možnost přidání přílohy.",
                            Priority = 3,
                            Status = 2,
                            StepName = "Postup",
                            TaskId = 16
                        },
                        new
                        {
                            Id = 28,
                            Deadline = new DateTime(2024, 2, 28, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "K jednotlivým částem kódu vytvořit unit testy pro zjištění funkčnosti.",
                            Priority = 1,
                            Status = 2,
                            StepName = "Zadání",
                            TaskId = 18
                        },
                        new
                        {
                            Id = 29,
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Po vložení přeslimitního počtu znaků se nic nestane. Oprava: Přidán atribut pro validaci",
                            DoneAt = new DateTime(2024, 2, 23, 23, 12, 30, 129, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Detail & Nový",
                            TaskId = 19
                        },
                        new
                        {
                            Id = 30,
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "U položek Termín se po stisknutí na tlačítko Vymazat a Uložit nastaví datum na 01.01.0001 Oprava: Nastavena defaultní hodnota pro parametr Termín",
                            DoneAt = new DateTime(2024, 2, 23, 23, 12, 30, 129, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 1,
                            StepName = "Detail & Nový",
                            TaskId = 19
                        },
                        new
                        {
                            Id = 31,
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Textové pole je moc krátké pro delší zprávu",
                            Priority = 1,
                            Status = 1,
                            StepName = "Chat",
                            TaskId = 19
                        });
                });

            modelBuilder.Entity("TaskEvidence.Models.CompanyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "desc1",
                            Name = "BORS Holding",
                            State = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "desc2",
                            Name = "BORS Service",
                            State = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "desc3",
                            Name = "BORS Logistics",
                            State = 1
                        });
                });

            modelBuilder.Entity("TaskEvidence.Models.TaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Orderer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Solver")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 3, 1, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Vytvoření systému pro evidenci úkolů",
                            DoneAt = new DateTime(2024, 2, 23, 20, 12, 40, 418, DateTimeKind.Unspecified),
                            Orderer = "Honza Novák",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 23, 19, 27, 24, 609, DateTimeKind.Unspecified),
                            Solver = "Pavel Stříž",
                            State = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 2, 24, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Přidání javascriptu pro zvýraznění selectu v tabulce",
                            DoneAt = new DateTime(2024, 2, 23, 20, 7, 30, 807, DateTimeKind.Unspecified),
                            Orderer = "Josef Dvořák",
                            Priority = 3,
                            PublishedAt = new DateTime(2024, 2, 23, 19, 28, 13, 861, DateTimeKind.Unspecified),
                            Solver = "Honza Novák",
                            State = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 2, 24, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Přidání css stylu pro grid",
                            DoneAt = new DateTime(2024, 2, 23, 20, 7, 35, 831, DateTimeKind.Unspecified),
                            Orderer = "Pavel Stříž",
                            Priority = 3,
                            PublishedAt = new DateTime(2024, 2, 23, 19, 29, 7, 762, DateTimeKind.Unspecified),
                            Solver = "Honza Novák",
                            State = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Company = "BORS Service",
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Upravení logiky pro zápis Deadline",
                            Orderer = "Pavel Stříž",
                            Priority = 2,
                            PublishedAt = new DateTime(2024, 2, 23, 19, 32, 13, 919, DateTimeKind.Unspecified),
                            Solver = "Josef Dvořák",
                            State = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 5,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Přejmenování sloupce v databázi",
                            Orderer = "Josef Dvořák",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 23, 19, 33, 24, 150, DateTimeKind.Unspecified),
                            Solver = "Pavel Stříž",
                            State = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 6,
                            Company = "BORS Logistics",
                            Deadline = new DateTime(2024, 2, 26, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Upravení datového typu sloupce v databázi.",
                            DoneAt = new DateTime(2024, 2, 23, 20, 8, 16, 719, DateTimeKind.Unspecified),
                            Orderer = "Pavel Stříž",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 23, 19, 35, 28, 9, DateTimeKind.Unspecified),
                            Solver = "Josef Dvořák",
                            State = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Vytvoření pohledů",
                            DoneAt = new DateTime(2024, 2, 23, 20, 8, 33, 381, DateTimeKind.Unspecified),
                            Orderer = "Honza Novák",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 23, 19, 38, 48, 432, DateTimeKind.Unspecified),
                            Solver = "Pavel Stříž",
                            State = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 2, 27, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Discard Feature",
                            Orderer = "Pavel Stříž",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 23, 19, 42, 10, 842, DateTimeKind.Unspecified),
                            Solver = "Honza Novák",
                            State = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 9,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 2, 28, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Změna tagů",
                            Orderer = "Josef Dvořák",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 23, 19, 43, 27, 900, DateTimeKind.Unspecified),
                            Solver = "Pavel Stříž",
                            State = 1,
                            Status = 3
                        },
                        new
                        {
                            Id = 10,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 2, 28, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Implementace komunikace formou chatu",
                            DoneAt = new DateTime(2024, 2, 23, 20, 9, 0, 380, DateTimeKind.Unspecified),
                            Orderer = "Honza Novák",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 23, 19, 51, 8, 242, DateTimeKind.Unspecified),
                            Solver = "Pavel Stříž",
                            State = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            Company = "BORS Service",
                            Deadline = new DateTime(2024, 2, 29, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Rozdělení kódu",
                            DoneAt = new DateTime(2024, 2, 23, 20, 9, 19, 487, DateTimeKind.Unspecified),
                            Orderer = "Honza Novák",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 23, 19, 53, 10, 937, DateTimeKind.Unspecified),
                            Solver = "Josef Dvořák",
                            State = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 2, 28, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Oprava chyb při komunikaci client-server",
                            DoneAt = new DateTime(2024, 2, 23, 20, 9, 39, 884, DateTimeKind.Unspecified),
                            Orderer = "Josef Dvořák",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 23, 19, 56, 1, 268, DateTimeKind.Unspecified),
                            Solver = "Pavel Stříž",
                            State = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            Company = "BORS Logistics",
                            Deadline = new DateTime(2024, 2, 27, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Přidání validací polí na frontendu",
                            Orderer = "Josef Dvořák",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 23, 19, 57, 1, 64, DateTimeKind.Unspecified),
                            Solver = "Honza Novák",
                            State = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 14,
                            Company = "BORS Logistics",
                            Deadline = new DateTime(2024, 2, 24, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Přidání validací polí na frontendu",
                            Orderer = "Pavel Stříž",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 23, 19, 58, 4, 53, DateTimeKind.Unspecified),
                            Solver = "Honza Novák",
                            State = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 15,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Přidat script pro simulaci dat",
                            DoneAt = new DateTime(2024, 2, 23, 20, 10, 23, 605, DateTimeKind.Unspecified),
                            Orderer = "Honza Novák",
                            Priority = 3,
                            PublishedAt = new DateTime(2024, 2, 23, 20, 0, 13, 893, DateTimeKind.Unspecified),
                            Solver = "Pavel Stříž",
                            State = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Možnost přidání přílohy",
                            Orderer = "Pavel Stříž",
                            Priority = 3,
                            PublishedAt = new DateTime(2024, 2, 23, 20, 1, 58, 293, DateTimeKind.Unspecified),
                            Solver = "Honza Novák",
                            State = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 17,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 2, 24, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Refaktoring jednotlivých částí kódu.",
                            DoneAt = new DateTime(2024, 2, 23, 20, 10, 39, 579, DateTimeKind.Unspecified),
                            Orderer = "Honza Novák",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 23, 20, 2, 40, 263, DateTimeKind.Unspecified),
                            Solver = "Pavel Stříž",
                            State = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 2, 28, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Vytvoření unit testů",
                            Orderer = "Pavel Stříž",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 23, 20, 5, 52, 375, DateTimeKind.Unspecified),
                            Solver = "Josef Dvořák",
                            State = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 19,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Regresní testy",
                            Orderer = "Pavel",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 23, 23, 10, 45, 141, DateTimeKind.Unspecified),
                            Solver = "Pavel Stříž",
                            State = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            Company = "BORS Holding",
                            Deadline = new DateTime(2024, 2, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Description = "Upload projektu na github a předání",
                            DoneAt = new DateTime(2024, 2, 23, 20, 10, 52, 427, DateTimeKind.Unspecified),
                            Orderer = "Josef Dvořák",
                            Priority = 1,
                            PublishedAt = new DateTime(2024, 2, 24, 20, 6, 27, 11, DateTimeKind.Unspecified),
                            Solver = "Pavel Stříž",
                            State = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("TaskEvidence.Shared.Models.AttachmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskAttachments", (string)null);
                });

            modelBuilder.Entity("TaskEvidence.Shared.Models.MessageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("PublishedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskMessages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "Toto je testovací zpráva",
                            PublishedAt = new DateTime(2024, 2, 24, 0, 28, 48, 935, DateTimeKind.Unspecified),
                            TaskId = 1,
                            UserName = "Pavel Stříž"
                        },
                        new
                        {
                            Id = 2,
                            Message = "",
                            PublishedAt = new DateTime(2024, 2, 24, 0, 28, 56, 530, DateTimeKind.Unspecified),
                            TaskId = 1,
                            UserName = "Honza Novák"
                        },
                        new
                        {
                            Id = 3,
                            Message = "Toto je testovací zpráva.",
                            PublishedAt = new DateTime(2024, 2, 24, 0, 30, 7, 930, DateTimeKind.Unspecified),
                            TaskId = 4,
                            UserName = "Josef Dvořák"
                        },
                        new
                        {
                            Id = 4,
                            Message = "Toto je testovací zpráva.",
                            PublishedAt = new DateTime(2024, 2, 24, 0, 30, 14, 253, DateTimeKind.Unspecified),
                            TaskId = 4,
                            UserName = "Honza Novák"
                        },
                        new
                        {
                            Id = 5,
                            Message = "Toto je testovací zpráva.",
                            PublishedAt = new DateTime(2024, 2, 24, 0, 30, 46, 358, DateTimeKind.Unspecified),
                            TaskId = 7,
                            UserName = "Pavel Stříž"
                        },
                        new
                        {
                            Id = 6,
                            Message = "Toto je testovací zpráva.",
                            PublishedAt = new DateTime(2024, 2, 24, 0, 30, 54, 753, DateTimeKind.Unspecified),
                            TaskId = 7,
                            UserName = "Honza Novák"
                        },
                        new
                        {
                            Id = 7,
                            Message = "Toto je testovací zpráva.",
                            PublishedAt = new DateTime(2024, 2, 24, 0, 31, 6, 905, DateTimeKind.Unspecified),
                            TaskId = 17,
                            UserName = "Josef Dvořák"
                        },
                        new
                        {
                            Id = 8,
                            Message = "Toto je testovací zpráva.",
                            PublishedAt = new DateTime(2024, 2, 24, 0, 31, 18, 869, DateTimeKind.Unspecified),
                            TaskId = 17,
                            UserName = "Pavel Stříž"
                        });
                });

            modelBuilder.Entity("TaskEvidence.Models.ChecklistModel", b =>
                {
                    b.HasOne("TaskEvidence.Models.TaskModel", "Task")
                        .WithMany("Checklist")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskEvidence.Shared.Models.AttachmentModel", b =>
                {
                    b.HasOne("TaskEvidence.Models.TaskModel", "Task")
                        .WithMany("Attachments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskEvidence.Shared.Models.MessageModel", b =>
                {
                    b.HasOne("TaskEvidence.Models.TaskModel", "Task")
                        .WithMany("Messages")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskEvidence.Models.TaskModel", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Checklist");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
